services:
  - type: web
    name: newsroomonline
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "newsroomonline.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://newsroomonline.onrender.com"
      - key: SITE_URL
        value: "https://newsroomonline.onrender.com"
